PLUGIN-78 Zendesk batch source
rostyslavmorozov/zendesk pull request #1
Opened 2019-10-16 19:08 UTC by rostyslavmorozov

Zendesk Single Object Batch Source

2019-10-17 14:54 UTC, aonischuk requested changes

2019-10-17 14:54 UTC, aonischuk commented on docs/ZendeskBatchSource-batchsource.md
> +https://support.zendesk.com/hc/en-us/articles/226022787-Generating-a-new-API-token-
Can we insert this using MD link syntax?

2019-10-17 14:54 UTC, aonischuk commented on docs/ZendeskBatchSource-batchsource.md
> +**Admin Email:** Zendesk's admin email.
Zendesk admin email.

Not Zendesk's. Same for the other usages.

2019-10-17 14:54 UTC, aonischuk commented on docs/ZendeskBatchSource-batchsource.md
> +**Max Retry Count:** Maximum number of retries can take.
Please make this sentence grammatically correct.

2019-10-17 14:54 UTC, aonischuk commented on docs/ZendeskBatchSource-batchsource.md
> +**Connect Timeout:** Maximum time in seconds connection initialization is allowed to take.
"is allowed to" -> "can"

2019-10-17 14:54 UTC, aonischuk commented on docs/ZendeskBatchSource-batchsource.md
> +**Read Timeout:** Maximum time in seconds fetching data from the server is allowed to take.
"is allowed to" -> "can"

2019-10-17 14:54 UTC, aonischuk commented on pom.xml
> +    <hydrator.version>2.2.0</hydrator.version>
2.3.0-SNAPSHOT

2019-10-17 14:54 UTC, aonischuk commented on pom.xml
> +    <hadoop.version>2.3.0</hadoop.version>
2.8.0

2019-10-17 14:54 UTC, aonischuk commented on src/main/java/io/cdap/plugin/zendesk/source/batch/BaseZendeskBatchSourceConfig.java
> +  @Description("Zendesk start_date filter. " +
This two sentences does not make sense together. Please rewrite.

2019-10-17 14:54 UTC, aonischuk commented on src/main/java/io/cdap/plugin/zendesk/source/batch/BaseZendeskBatchSourceConfig.java
> +  @Description("Zendesk end_date filter. " +
same

2019-10-17 14:54 UTC, aonischuk commented on src/main/java/io/cdap/plugin/zendesk/source/batch/BaseZendeskBatchSourceConfig.java
> +public class BaseZendeskBatchSourceConfig extends BaseZendeskSourceConfig {
Please fix all the descriptions the same way you did in MD doc.

2019-10-17 14:54 UTC, aonischuk commented on src/main/java/io/cdap/plugin/zendesk/source/batch/BaseZendeskBatchSourceConfig.java
> +      return "https://%s.zendesk.com/api/v2/%s";
just add a default value in widget and make it not nullable. Why do we need this hardcode?

2019-10-17 14:54 UTC, aonischuk commented on src/main/java/io/cdap/plugin/zendesk/source/common/config/BaseZendeskSourceConfig.java
> +      IdUtils.validateId(referenceName);
IdUtils.validateReferenceName from 2.3.0-SNAPSHOT.

2019-10-17 14:54 UTC, aonischuk commented on src/main/java/io/cdap/plugin/zendesk/source/batch/BaseZendeskBatchSourceConfig.java
> +            "Property 'Start Date' can't be empty.",
must not be empty.

2019-10-17 14:54 UTC, aonischuk commented on src/main/java/io/cdap/plugin/zendesk/source/batch/BaseZendeskBatchSourceConfig.java
> +          .withStacktrace(e.getStackTrace());
I don't think stack trace adds any valuable info we should remove this.

2019-10-17 14:54 UTC, aonischuk commented on src/main/java/io/cdap/plugin/zendesk/source/batch/ZendeskBatchSource.java
> +    pipelineConfigurer.getStageConfigurer().setOutputSchema(config.getSchema(failureCollector));
```
if (!config.containsMacro(BaseZendeskSourceConfig.PROPERTY_OBJECTS_TO_PULL)) {
  pipelineConfigurer.getStageConfigurer().setOutputSchema(config.getSchema(failureCollector));
}
```

2019-10-17 14:54 UTC, aonischuk commented on src/main/java/io/cdap/plugin/zendesk/source/batch/ZendeskBatchSourceConfig.java
> +public class ZendeskBatchSourceConfig extends BaseZendeskBatchSourceConfig {
can we merge these in one class?

2019-10-17 14:54 UTC, aonischuk commented on src/main/java/io/cdap/plugin/zendesk/source/batch/ZendeskBatchSourceConfig.java
> +    } catch (Exception e) {
Catch a more specific type of exception?

2019-10-17 14:54 UTC, aonischuk commented on src/main/java/io/cdap/plugin/zendesk/source/batch/ZendeskBatchSourceConfig.java
> +      collector.addFailure(String.format("Unable to parse output schema: %s", schema),
Unable to parse output schema: '%s'

2019-10-17 14:54 UTC, aonischuk commented on src/main/java/io/cdap/plugin/zendesk/source/batch/ZendeskBatchSourceConfig.java
> +                           "Ensure 'Schema' is specified.")
If it's not specified it would be null, and not exception. So this message is wrong I think.

2019-10-17 14:54 UTC, aonischuk commented on src/main/java/io/cdap/plugin/zendesk/source/batch/ZendeskInputFormat.java
> +        .map(object -> new ZendeskSplit(subdomain, object)))
nit: fix indentation

2019-10-17 14:54 UTC, aonischuk commented on src/main/java/io/cdap/plugin/zendesk/source/batch/ZendeskRecordReader.java
> +import static io.cdap.plugin.zendesk.source.batch.util.ZendeskBatchSourceConstants.PROPERTY_CONFIG_JSON;
don't use static imports. It's against our codestyle.

2019-10-17 14:54 UTC, aonischuk commented on src/main/java/io/cdap/plugin/zendesk/source/batch/ZendeskRecordReader.java
> +    }
Why are we re-building the same record one more time?

2019-10-17 14:54 UTC, aonischuk commented on src/main/java/io/cdap/plugin/zendesk/source/batch/http/HttpUtil.java
> +  public static CloseableHttpClient createHttpClient(BaseZendeskBatchSourceConfig config) {
Why are we triggering manual HTTP requests if there is a Zendesk Java client? This would be much harder to maintain. Can we re-do it using client?

2019-10-17 14:54 UTC, aonischuk commented on src/main/java/io/cdap/plugin/zendesk/source/common/ObjectType.java
> +import static io.cdap.plugin.zendesk.source.common.ObjectTypeSchemaConstants.SCHEMA_ARTICLE_COMMENTS;
same about static imports

2019-10-17 14:54 UTC, aonischuk commented on src/main/java/io/cdap/plugin/zendesk/source/common/ObjectTypeSchemaConstants.java
> +    Schema.Field.of("author_id", Schema.nullableOf(Schema.of(Schema.Type.LONG))),
I may be mistaken, but I think we use camel case for field names. Can you please check and re-do all names if that's the case?

2019-10-17 14:54 UTC, aonischuk commented on src/main/java/io/cdap/plugin/zendesk/source/common/config/BaseZendeskSourceConfig.java
> +  @Description("Zendesk Admin's Email.")
Admin's -> Admin

2019-10-17 14:54 UTC, aonischuk commented on src/main/java/io/cdap/plugin/zendesk/source/common/config/BaseZendeskSourceConfig.java
> +  public void validate(FailureCollector collector) {
Can we validate if connection is possible and authentication using given credentials works?

2019-10-17 14:54 UTC, aonischuk commented on src/main/java/io/cdap/plugin/zendesk/source/common/config/BaseZendeskSourceConfig.java
> +      collector.addFailure(String.format("Provided email is invalid: %s", adminEmail), null)
Email '%s' is invalid.

2019-10-17 14:54 UTC, aonischuk commented on src/test/java/io/cdap/plugin/zendesk/source/batch/BaseZendeskBatchSourceConfigTest.java
> +  public void testGetZendeskBaseUrl() {
remover since we will not have default value in code

2019-10-17 14:54 UTC, aonischuk commented on src/test/java/io/cdap/plugin/zendesk/source/batch/BaseZendeskBatchSourceConfigTest.java
> +  public void testGetZendeskBaseUrlNull() {
remover since we will not have default value in code

2019-10-17 14:54 UTC, aonischuk commented on src/test/java/io/cdap/plugin/zendesk/source/batch/BaseZendeskBatchSourceConfigTest.java
> +  public void testGetZendeskBaseUrlEmpty() {
remover since we will not have default value in code

2019-10-17 14:54 UTC, aonischuk commented on widgets/ZendeskBatchSource-batchsource.json
> +          "plugin-function": {
plugin-functions are deprecated. Remove this. We generate schema now by setting it in pipelineConfigurer. So the user presses "Validate" button to get it.

2019-10-17 14:54 UTC, aonischuk commented on widgets/ZendeskBatchSource-batchsource.json
> +              "received_with_comment",
camel case.

2019-10-17 14:54 UTC, aonischuk commented on widgets/ZendeskBatchSource-batchsource.json
> +          "widget-type": "hidden",
why do we have this as hidden? Was is the intent behind it? If user cannot configure it, we should remove this probably. Unless I am missing something here.

2019-10-17 14:54 UTC, aonischuk commented on widgets/ZendeskMultiObjects-batchsource.json
> +{
If this pull request does not contain multi objects implementation. We should remove this from it.

2019-10-17 21:54 UTC, rostyslavmorozov commented on src/main/java/io/cdap/plugin/zendesk/source/batch/http/HttpUtil.java
> +  public static CloseableHttpClient createHttpClient(BaseZendeskBatchSourceConfig config) {
Zendesk Java client covers not all endpoints (approximately 40-50%) and it is not extensible. I removed dependency on it.

2019-10-17 21:55 UTC, rostyslavmorozov commented on widgets/ZendeskBatchSource-batchsource.json
> +          "widget-type": "hidden",
This is config property used to build URL based on specified subdomains. User shouldn't have ability to modify it.

2019-10-17 22:16 UTC, rostyslavmorozov commented on docs/ZendeskBatchSource-batchsource.md
> +https://support.zendesk.com/hc/en-us/articles/226022787-Generating-a-new-API-token-
Done

2019-10-17 22:16 UTC, rostyslavmorozov commented on docs/ZendeskBatchSource-batchsource.md
> +**Admin Email:** Zendesk's admin email.
Done

2019-10-17 22:17 UTC, rostyslavmorozov commented on docs/ZendeskBatchSource-batchsource.md
> +**Max Retry Count:** Maximum number of retries can take.
Done

2019-10-17 22:17 UTC, rostyslavmorozov commented on docs/ZendeskBatchSource-batchsource.md
> +**Connect Timeout:** Maximum time in seconds connection initialization is allowed to take.
Done

2019-10-17 22:17 UTC, rostyslavmorozov commented on docs/ZendeskBatchSource-batchsource.md
> +**Read Timeout:** Maximum time in seconds fetching data from the server is allowed to take.
Done

2019-10-17 22:17 UTC, rostyslavmorozov commented on pom.xml
> +    <hydrator.version>2.2.0</hydrator.version>
Done

2019-10-17 22:17 UTC, rostyslavmorozov commented on pom.xml
> +    <hadoop.version>2.3.0</hadoop.version>
Done

2019-10-17 22:17 UTC, rostyslavmorozov commented on src/main/java/io/cdap/plugin/zendesk/source/batch/BaseZendeskBatchSourceConfig.java
> +  @Description("Zendesk start_date filter. " +
Done

2019-10-17 22:17 UTC, rostyslavmorozov commented on src/main/java/io/cdap/plugin/zendesk/source/batch/BaseZendeskBatchSourceConfig.java
> +  @Description("Zendesk end_date filter. " +
Done

2019-10-17 22:18 UTC, rostyslavmorozov commented on src/main/java/io/cdap/plugin/zendesk/source/batch/BaseZendeskBatchSourceConfig.java
> +public class BaseZendeskBatchSourceConfig extends BaseZendeskSourceConfig {
Done

2019-10-17 22:18 UTC, rostyslavmorozov commented on src/main/java/io/cdap/plugin/zendesk/source/batch/BaseZendeskBatchSourceConfig.java
> +      return "https://%s.zendesk.com/api/v2/%s";
Done

2019-10-17 22:18 UTC, rostyslavmorozov commented on src/main/java/io/cdap/plugin/zendesk/source/common/config/BaseZendeskSourceConfig.java
> +      IdUtils.validateId(referenceName);
Done

2019-10-17 22:18 UTC, rostyslavmorozov commented on src/main/java/io/cdap/plugin/zendesk/source/batch/BaseZendeskBatchSourceConfig.java
> +            "Property 'Start Date' can't be empty.",
Done

2019-10-17 22:18 UTC, rostyslavmorozov commented on src/main/java/io/cdap/plugin/zendesk/source/batch/BaseZendeskBatchSourceConfig.java
> +          .withStacktrace(e.getStackTrace());
Done

2019-10-17 22:18 UTC, rostyslavmorozov commented on src/main/java/io/cdap/plugin/zendesk/source/batch/ZendeskBatchSource.java
> +    pipelineConfigurer.getStageConfigurer().setOutputSchema(config.getSchema(failureCollector));
Done

2019-10-17 22:19 UTC, rostyslavmorozov commented on src/main/java/io/cdap/plugin/zendesk/source/batch/ZendeskBatchSourceConfig.java
> +public class ZendeskBatchSourceConfig extends BaseZendeskBatchSourceConfig {
Done

2019-10-17 22:19 UTC, rostyslavmorozov commented on src/main/java/io/cdap/plugin/zendesk/source/batch/ZendeskBatchSourceConfig.java
> +    } catch (Exception e) {
Done

2019-10-17 22:19 UTC, rostyslavmorozov commented on src/main/java/io/cdap/plugin/zendesk/source/batch/ZendeskBatchSourceConfig.java
> +      collector.addFailure(String.format("Unable to parse output schema: %s", schema),
Done

2019-10-17 22:19 UTC, rostyslavmorozov commented on src/main/java/io/cdap/plugin/zendesk/source/batch/ZendeskBatchSourceConfig.java
> +                           "Ensure 'Schema' is specified.")
Done

2019-10-17 22:19 UTC, rostyslavmorozov commented on src/main/java/io/cdap/plugin/zendesk/source/batch/ZendeskInputFormat.java
> +        .map(object -> new ZendeskSplit(subdomain, object)))
Done

2019-10-17 22:19 UTC, rostyslavmorozov commented on src/main/java/io/cdap/plugin/zendesk/source/batch/ZendeskRecordReader.java
> +import static io.cdap.plugin.zendesk.source.batch.util.ZendeskBatchSourceConstants.PROPERTY_CONFIG_JSON;
Done

2019-10-17 22:19 UTC, rostyslavmorozov commented on src/main/java/io/cdap/plugin/zendesk/source/batch/ZendeskRecordReader.java
> +    }
Done

2019-10-17 22:20 UTC, rostyslavmorozov commented on src/main/java/io/cdap/plugin/zendesk/source/common/ObjectType.java
> +import static io.cdap.plugin.zendesk.source.common.ObjectTypeSchemaConstants.SCHEMA_ARTICLE_COMMENTS;
Done

2019-10-17 22:20 UTC, rostyslavmorozov commented on src/main/java/io/cdap/plugin/zendesk/source/common/ObjectTypeSchemaConstants.java
> +    Schema.Field.of("author_id", Schema.nullableOf(Schema.of(Schema.Type.LONG))),
Done

2019-10-17 22:20 UTC, rostyslavmorozov commented on src/main/java/io/cdap/plugin/zendesk/source/common/config/BaseZendeskSourceConfig.java
> +  @Description("Zendesk Admin's Email.")
Done

2019-10-17 22:20 UTC, rostyslavmorozov commented on src/main/java/io/cdap/plugin/zendesk/source/common/config/BaseZendeskSourceConfig.java
> +  public void validate(FailureCollector collector) {
Done

2019-10-17 22:20 UTC, rostyslavmorozov commented on src/main/java/io/cdap/plugin/zendesk/source/common/config/BaseZendeskSourceConfig.java
> +      collector.addFailure(String.format("Provided email is invalid: %s", adminEmail), null)
Done

2019-10-17 22:20 UTC, rostyslavmorozov commented on src/test/java/io/cdap/plugin/zendesk/source/batch/BaseZendeskBatchSourceConfigTest.java
> +  public void testGetZendeskBaseUrl() {
Done

2019-10-17 22:21 UTC, rostyslavmorozov commented on src/test/java/io/cdap/plugin/zendesk/source/batch/BaseZendeskBatchSourceConfigTest.java
> +  public void testGetZendeskBaseUrlNull() {
Done

2019-10-17 22:21 UTC, rostyslavmorozov commented on src/test/java/io/cdap/plugin/zendesk/source/batch/BaseZendeskBatchSourceConfigTest.java
> +  public void testGetZendeskBaseUrlEmpty() {
Done

2019-10-17 22:21 UTC, rostyslavmorozov commented on widgets/ZendeskBatchSource-batchsource.json
> +          "plugin-function": {
Done

2019-10-17 22:21 UTC, rostyslavmorozov commented on widgets/ZendeskBatchSource-batchsource.json
> +              "received_with_comment",
Done

2019-10-17 22:21 UTC, rostyslavmorozov commented on widgets/ZendeskMultiObjects-batchsource.json
> +{
Done

2019-10-18 08:52 UTC, aonischuk approved these changes

2019-10-18 09:34 UTC, closed without merging