PLUGIN-78 - Zendesk Batch Source Multi Object plugin
rostyslavmorozov/zendesk pull request #2
Opened 2019-10-22 06:51 UTC by rostyslavmorozov

WIKI: https://wiki.cask.co/display/CE/Zendesk+plugins
JIRA: https://issues.cask.co/browse/PLUGIN-78

Included:
- Multi Object Batch Source

2019-10-22 18:58 UTC, aonischuk requested changes

2019-10-22 18:58 UTC, aonischuk commented on docs/ZendeskBatchMultiSource-batchsource.md
> +**Subdomains:** List of Zendesk Subdomains to read object from.
"to read **the** object**s** from"

2019-10-22 18:58 UTC, aonischuk commented on docs/ZendeskBatchMultiSource-batchsource.md
> +**Start Date:** Filter data to only include records where Zendesk modified date is greater than
Filter data to include only records which have Zendesk modified date greater ...

2019-10-22 18:58 UTC, aonischuk commented on docs/ZendeskBatchMultiSource-batchsource.md
> +**End Date:** Filter data to only include records where Zendesk modified date is less than
same

2019-10-22 18:58 UTC, aonischuk commented on docs/ZendeskBatchMultiSource-batchsource.md
> +**Satisfaction Ratings Score:** Score filter for Satisfaction Ratings object.
It's hard to understand what this is from this description.

2019-10-22 18:58 UTC, aonischuk commented on src/main/java/io/cdap/plugin/zendesk/source/batch/ZendeskBatchMultiSource.java
> +    pipelineConfigurer.getStageConfigurer().setOutputSchema(null);
why do we clear schema during validation. Is this something intentional?

2019-10-22 18:58 UTC, aonischuk commented on src/main/java/io/cdap/plugin/zendesk/source/batch/ZendeskBatchMultiSource.java
> +  private void validateConfiguration(FailureCollector failureCollector) {
Do we need a separate method for only two lines of code?

2019-10-22 18:58 UTC, aonischuk commented on src/main/java/io/cdap/plugin/zendesk/source/common/config/BaseZendeskSourceConfig.java
> +      collector.addFailure(String.format("Provided email is invalid: %s", adminEmail), null)
'%s' is not a valid email.

2019-10-22 18:58 UTC, aonischuk commented on widgets/ZendeskBatchMultiSource-batchsource.json
> +          "widget-type": "textbox",
is this secret info or not? If it is we should use "password".

2019-10-23 05:10 UTC, rostyslavmorozov commented on docs/ZendeskBatchMultiSource-batchsource.md
> +**Subdomains:** List of Zendesk Subdomains to read object from.
Done

2019-10-23 05:11 UTC, rostyslavmorozov commented on docs/ZendeskBatchMultiSource-batchsource.md
> +**Start Date:** Filter data to only include records where Zendesk modified date is greater than
Done

2019-10-23 05:11 UTC, rostyslavmorozov commented on docs/ZendeskBatchMultiSource-batchsource.md
> +**End Date:** Filter data to only include records where Zendesk modified date is less than
Done

2019-10-23 05:11 UTC, rostyslavmorozov commented on docs/ZendeskBatchMultiSource-batchsource.md
> +**Satisfaction Ratings Score:** Score filter for Satisfaction Ratings object.
Done

2019-10-23 05:11 UTC, rostyslavmorozov commented on src/main/java/io/cdap/plugin/zendesk/source/batch/ZendeskBatchMultiSource.java
> +    pipelineConfigurer.getStageConfigurer().setOutputSchema(null);
Done

2019-10-23 05:11 UTC, rostyslavmorozov commented on src/main/java/io/cdap/plugin/zendesk/source/batch/ZendeskBatchMultiSource.java
> +  private void validateConfiguration(FailureCollector failureCollector) {
Done

2019-10-23 05:11 UTC, rostyslavmorozov commented on src/main/java/io/cdap/plugin/zendesk/source/common/config/BaseZendeskSourceConfig.java
> +      collector.addFailure(String.format("Provided email is invalid: %s", adminEmail), null)
Done

2019-10-23 05:11 UTC, rostyslavmorozov commented on widgets/ZendeskBatchMultiSource-batchsource.json
> +          "widget-type": "textbox",
Done

2019-10-24 09:47 UTC, aonischuk approved these changes

2019-10-24 09:49 UTC, merged